services:
  prod-app-server:
    restart: always
    image: prod-app-server
    container_name: prod-app-server
    environment:
      - DEBUG=False
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    ports:
      - "8000:8000"


  prod-app-daphne:
    restart: always
    image: prod-app-daphne
    container_name: prod-app-daphne
    environment:
      - DEBUG=False
    ports:
      - "6000:6000"
    build:
      context: .
      dockerfile: dockerfiles/daphne.Dockerfile


  prod-app-pgadmin4:
    restart: always
    image: prod-app-pgadmin4
    container_name: prod-app-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL = xpert@xpertinc.co.kr
      PGADMIN_DEFAULT_PASSWORD = 1q2w3e!Q
    ports:
      - "5050:8080"
    build:
      context: .
      dockerfile: dockerfiles/pgadmin4.Dockerfile


  prod-app-redis:
    image: redis:6.2.13-bookworm
    container_name: prod-redis
    ports:
      - "6379:6379"


  prod-celery-worker:
    restart: always
    image: prod-celery-worker
    container_name: prod-celery-worker
    environment:
      - CELERY_WORKER=True
      - DEBUG=False
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    depends_on:
      - prod-redis


  prod-celery-beat:
    restart: always
    image: prod-celery-beat
    container_name: prod-celery-beat
    environment:
      - CELERY_BEAT=True
      - DEBUG=False
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    depends_on:
      - prod-app-redis



