services:
  dev-app-server:
    restart: always
    image: dev-app-server
    container_name: dev-app-server
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - dev-app-db

  dev-app-db:
    restart: always
    image: postgres:15.4-alpine
    container_name:  dev-app-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1q2w3e!Q
      - POSTGRES_DB=dev-app-db
    volumes:
      - ./data/dev/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dev-app-pgadmin4:
      restart: always
      image: dev-app-pgadmin4
      container_name: dev-app-pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@xpertinc.co.kr
        - PGADMIN_DEFAULT_PASSWORD=1q2w3e!Q
      volumes:
        - ./data/dev/pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      depends_on:
        - dev-app-db
      build:
        context: .
        dockerfile: dockerfiles/pgadmin4.Dockerfile
  
  dev-app-redis:
    image: redis:6.2.13-bookworm
    container_name: dev-app-redis
    ports:
      - "6379:6379"

  dev-app-celery-worker:
      restart: always
      image: dev-app-celery-worker
      container_name: dev-app-celery-worker
      environment:
        - CELERY_WORKER=True
        - DEBUG=True
      build: 
        context: .
        dockerfile: dockerfiles/django.Dockerfile
      depends_on:
        - dev-app-db
        - dev-app-redis
        
  dev-app-celery-beat:
      restart: always
      image: dev-app-celery-beat
      container_name: dev-app-celery-beat
      environment:
        - CELERY_BEAT=True
        - DEBUG=True
      build: 
        context: .
        dockerfile: dockerfiles/django.Dockerfile
      depends_on:
        - dev-app-db
        - dev-app-redis
  

