services:
  prod-app-server:
    restart: always
    image: prod-app-server
    container_name: prod-app-server
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    ports:
      - "8000:8000"


  #  prod-app-daphne:
  #    restart: always
  #    image: prod-app-daphne
  #    container_name: prod-app-daphne
  #    ports:
  #      - "6000:6000"
  #    build:
  #      context: .
  #      dockerfile: dockerfiles/daphne.Dockerfile


  prod-app-redis:
    image: redis:6.2.13-bookworm
    container_name: prod-redis
    ports:
      - "6379:6379"




