services:
  prod-csound-server:
    restart: always
    image: prod-csound-server
    container_name: prod-csound-server
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: dockerfiles/django.prod.Dockerfile
    ports:
      - "8000:8000"


  prod-csound-daphne:
    restart: always
    image: prod-csound-daphne
    container_name: prod-csound-daphne
    env_file:
      - env/prod.env
    ports:
      - "6000:6000"
    build:
      context: .
      dockerfile: dockerfiles/daphne.prod.Dockerfile


  prod-csound-pgadmin4:
    container_name: prod-csound-pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - env/prod.env
    ports: 
      - "5050:8080"


  prod-csound-nginx:
    container_name: prod-csound-nginx
    image: nginx:latest
    build: 
      context: .
      dockerfile: dockerfiles/nginx.prod.Dockerfile
    ports: 
      - 80:80
    depends_on:
      - prod-csound-server
      - prod-csound-daphne
      - prod-csound-pgadmin4
  

  prod-csound-redis:
    image: redis:6.2.13-bookworm
    container_name: prod-csound-redis
    ports:
      - "6379:6379"


