services:
  prod-app-server:
    restart: always
    image: prod-app-server
    container_name: prod-app-server
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: dockerfiles/django.Dockerfile
    ports:
      - "8000:8000"


  prod-app-daphne:
    restart: always
    image: prod-app-daphne
    container_name: prod-app-daphne
    env_file:
      - env/prod.env
    ports:
      - "6000:6000"
    build:
      context: .
      dockerfile: dockerfiles/daphne.Dockerfile


  prod-app-pgadmin4:
    container_name: prod-app-pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - env/prod.env
    ports:
      - "5050:8080"



  prod-app-redis:
    image: redis:6.2.13-bookworm
    container_name: prod-redis
    ports:
      - "6379:6379"

  prod-celery-worker:
    restart: always
    image: prod-celery-worker
    container_name: prod-celery-worker
    environment:
      - CELERY_WORKER=True
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: dockerfiles/django.prod.Dockerfile
    depends_on:
      - prod-redis

  prod-celery-beat:
    restart: always
    image: prod-celery-beat
    container_name: prod-celery-beat
    environment:
      - CELERY_BEAT=True
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: dockerfiles/django.prod.Dockerfile
    depends_on:
      - prod-app-redis



