services:
  prod-app-server:
    restart: always
    image: prod-app-server
    container_name: prod-app-server
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    build: 
      context: .
      dockerfile: dockerfiles/django.prod.Dockerfile
    ports:
      - "8000:8000"


  prod-app-daphne:
    restart: always
    image: prod-app-daphne
    container_name: prod-app-daphne
    env_file:
      - env/prod.env
    ports:
      - "6000:6000"
    build:
      context: .
      dockerfile: dockerfiles/daphne.prod.Dockerfile


  prod-app-pgadmin4:
    container_name: prod-app-pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - env/prod.env
    ports: 
      - "5050:8080"


  prod-app-nginx:
    container_name: prod-app-nginx
    image: nginx:latest
    build: 
      context: .
      dockerfile: dockerfiles/nginx.prod.Dockerfile
    ports: 
      - 80:80
    depends_on:
      - prod-app-server
      - prod-app-daphne
      - prod-app-pgadmin4
  

  prod-app-redis:
    image: redis:6.2.13-bookworm
    container_name: prod-app-redis
    ports:
      - "6379:6379"


